http:
  port: 9111
  token: "changeme"

metrics:
  tps:
    enabled: true
    interval: 1
  memory:
    enabled: true
    interval: 1
  player_count:
    enabled: true
    interval: 1
  player_ping:
    enabled: true
    interval: 1
  loaded_chunks:
    enabled: true
    interval: 1
    counting_method: "event"  # Options: "event" or "sampling"
  loaded_entities:
    enabled: true
    interval: 1
    counting_method: "event"  # Options: "event" or "sampling"
    count_types: false

  # Custom placeholder API metrics
  custom:
    minecraft_server_uptime:
      description: "Minecraft Server Uptime"
      type: "gauge"
      placeholder: "%server_online%"
      interval: 1
      per_player: false
    minecraft_mob_kills:
      description: "Amount of killed mobs per player"
      type: "gauge"
      placeholder: "%statistic_mob_kills%"
      interval: 1
      per_player: true